<template>
<!-- <v-card class="flex w-1/5">
    {{ pokemon.name }}
    <v-img v-if="pokemon.sprites" :src="pokemon.sprites.other['official-artwork'].front_default" class="w-1/2"/>
</v-card> -->

<div class="flex w-1/5 blur-in-expand">
        <div class="p-4 bg-white rounded-xl shadow-md overflow-hidden" :style="getBorderColor(pokemon.types)">
          <div class="md:flex md:flex-col">
            <span class="text-2xl text-indigo-600 font-semibold">#{{ pokemon.order }}</span>
            <div class="md:flex-shrink-0">
              <img
                class="h-48 w-full object-contain md:h-full md:w-48"
                :src="pokemon.sprites.other['official-artwork'].front_default"
                alt="Man looking at item at a store"
              />
            </div>
            <div class="p-8">
              <div class="text-xl text-indigo-600 font-semibold capitalize">
                {{pokemon.name}}
              </div>
              <div  class="text-gray-500 mb-5 inline-flex gap-2 mt-1">
               <v-chip small :color="$colors[typeInfo.type.name]" v-for="typeInfo in pokemon.types"> {{ typeInfo.type.name }} </v-chip>
              </div>
              <div class="flex mt-2 mb-2 flex-row flex-wrap gap-1">
                <div class="min-w-fit w-1/3 text-gray-500 pb-2 capitalize" v-for="statInfo in pokemon.stats">
                    {{statInfo.stat.name}}
                    <p className="text-gray-700 font-bold">{{ statInfo.base_stat }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</template>

<script setup lang="ts">

const { $colors}  = useNuxtApp();

const props = defineProps({
  pokemon: {
    type: Object,
    required: true,
  },
});
const { pokemon } = props;

const getBorderColor = (types: any) => {
    const hasMultipleColors = types.length > 1;
    let colorsBorder = [($colors as Record<string, string>)[types[0].type.name as string]];
    if(!hasMultipleColors) return `border: 3px solid ${colorsBorder[0]}`
    colorsBorder.push(($colors as Record<string, string>)[types[1].type.name as string]);
    return `
        border-left: 3px solid ${colorsBorder[0]};
        border-top: 3px solid ${colorsBorder[0]};
        border-right: 3px solid ${colorsBorder[1]};
        border-bottom: 3px solid ${colorsBorder[1]};
    `
    
}
</script>

<style>
.blur-in{
  animation:blur-in 0.4s linear both
}

@keyframes blur-in {
  0% {
    filter:blur(12px);
    opacity:0;
  }
  100% {
    filter:blur(0);
    opacity:1;
  }
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-in-expand{animation:blur-in-expand 0.4s linear both} @keyframes blur-in-expand{0%{transform:scale(0);filter:blur(12px);opacity:0}100%{transform:scale(1);filter:blur(0);opacity:1}}
</style>